# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Publish Release
run-name: publish-release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
