# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Publish Release (test)
run-name: publish-release-test

on:
  workflow_dispatch:
#  push:
#    tags: ["v*"]

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: ["build"]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - run: uv publish --trusted-publishing always --index testpypi
