# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Publish Release (test)
run-name: publish-release-test

on:
  workflow_dispatch:
#  push:
#    tags: ["v*"]

permissions:
  contents: read

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - run: uv publish --trusted-publishing always --index testpypi
